= DGIWG Catalogue Service for the Web 2.0 Conformance Test Suite

== Scope

This executable test suite (ETS) verifies that a DGIWG Catalogue Service for the Web 2.0 implementation conforms to https://portal.dgiwg.org/files/?artifact_id=68270&format=pdf[DGIWG Catalogue Service for the Web 2.0] and related standards. Conformance testing is a kind of "black box" testing that examines externally visible characteristics or behaviors of the SUT and is independent of any implementation details.

Several conformance classes are defined in the principal specifications; the ones
listed below are covered by this test suite:

* DGIWG_Basic_CSW
    - The DGIWG_Basic_CSW specifies requirements that all DGIWG Catalogue Service for the Web 2.0 have to implement.
* DGIWG_CSWT
    - The DGIWG_CSWT specifies requirements that transactional DGIWG Catalogue Service for the Web 2.0 have to implement.

== Test requirements

The documents listed below stipulate requirements that must be satisfied by a 
conforming implementation.

1. https://portal.dgiwg.org/files/?artifact_id=68270&format=pdf[DGIWG Catalogue Service for the Web 2.0]
2. OGC Catalogue Services Specification - 2.0.2 http://portal.opengeospatial.org/files/?artifact_id=20555[OGC 07-006r1]
3. ISO Metadata Application Profile CSW ISO - 1.0.1 https://portal.opengeospatial.org/files/?artifact_id=77855[OGC 07-045r1]

== Test suite structure

The test suite definition file (testng.xml) is located in the root package, 
`org.opengis.cite.cat20.dgiwg10`. A conformance class corresponds to a &lt;test&gt; element, each
of which includes a set of test classes that contain the actual test methods. 
The general structure of the test suite is shown in Table 1.

.Test suite structure
[cols="2,6a",options=header]
|===
|Conformance class
|Test classes

|Preconditions
|org.opengis.cite.cat20.dgiwg10.SuitePreconditions

|DGIWG_Basic_CSW
|
 * org.opengis.cite.cat20.dgiwg10.getcapabilities.*
 * org.opengis.cite.cat20.dgiwg10.getrecords.*
 * org.opengis.cite.cat20.dgiwg10.getrecordbyid.*

|DGIWG_CSWT
|org.opengis.cite.cat20.dgiwg10.transaction.*

|===

The Javadoc documentation provides more detailed information about the test 
methods that constitute the suite.

include::how-to-run-the-tests.adoc[]

== Using the REST API

Using the REST API of the TEAM Engine requires some run arguments. These ate summarized in Table 2.
The _Obligation_ descriptor can have the following values: M (mandatory), O (optional), or C (conditional).

.Test run arguments
[cols="1,1,1,6",options=header]
|===
|Name
|Value domain
|Obligation
|Description

|iut
|URI
|M
|A URI that refers to the implementation under test or metadata about it. Ampersand ('&amp;') characters must be percent-encoded as '%26'.

|===

== Used by ETS

The following record is required for the test issueHarvestRequest triggers a request harvesting this metadata record.

link:DMFMetadataRecord.xml[DMFMetadataRecord]